routes/admin.php
<?php
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'guest'], function(){
  Route::get('login', 'LoginController@showLoginForm')->name('login');
  Route::post('login', 'LoginController@login')->name('login.action');
});

Route::group(['middleware' => 'auth'], function(){
  Route::get('', 'DashboardController@index')->name('index');
  Route::post('logout', 'LoginController@logout')->name('logout');

  // profile
  Route::resource('profile', 'ProfileController')->only(['index', 'store']);

  // activity log
  Route::get('activity-log', 'ActivityLogController@index')->name('activity-log.index');
  Route::get('activity-log/api', 'ActivityLogController@api')->name('activity-log.api');

  // user
  Route::get('user/{id}/configure', 'UserController@configureForm')->name('user.configure');
  Route::post('user/{id}/configure', 'UserController@configure')->name('user.configure.action');
  Route::resource('user', 'UserController');

  // permission
  Route::resource('permission', 'PermissionController')->except('show');

  // role
  Route::get('role/{id}/configure', 'RoleController@configureForm')->name('role.configure');
  Route::post('role/{id}/configure', 'RoleController@configure')->name('role.configure.action');
  Route::resource('role', 'RoleController')->except('show');

  // teacher
  Route::resource('teacher', 'TeacherController');

  // STUDENT
  Route::resource('student', 'StudentController');

  // Examination
  Route::resource('examination', 'ExaminationController');
  Route::get('examination/{id}/detail', 'ExaminationController@detail')->name('examination.detail');
  Route::get('/get-detail-soal', 'ExaminationController@dataDetailSoal')->name('examination.get-detail-soal');
	Route::post('/examination/save-question-examination', 'ExaminationController@storeQuestion')->name('examination.save-question-examination');



  // Question
  Route::resource('question', 'QuestionController');
  Route::post('/images', 'QuestionController@uploadImage')->name('post.image');

  // Package Question
  Route::resource('question_package', 'QuestionPackageController');

  // Lesson
  Route::resource('subject', 'SubjectController');

  // Class
  Route::resource('class', 'ClassesController');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;

Route::get('/', function () {
  return redirect()->route('admin.index');
});

resources/views/layouts/dashboard_student/inc/breadcrumb.blade.php
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    @if (Route::is('admin.index'))
      Home
    @else
      <a href="{{ route('admin.index') }}">Home</a>
    @endif
  </li>

  @isset($breadcrumbs)
    @foreach ($breadcrumbs as $r)
    @if (!is_null($r[1]))
    <li class="breadcrumb-item">
      <a href="{{ $r[1] }}">{{ $r[0] }}</a>
    </li>
    @else
    <li class="breadcrumb-item">{{ $r[0] }}</li>
    @endif
    @endforeach      
  @endisset
</ol>

resources/views/layouts/dashboard_student/inc/footer.blade.php
<footer class="footer footer-static footer-light navbar-border">
  <p class="clearfix blue-grey lighten-2 text-sm-center mb-0 px-2">
    <span class="float-md-left d-block d-md-inline-block">
      Copyright &copy; 2020
    </span>
    <span class="float-md-right d-block d-md-inline-blockd-none d-lg-block">Hand-crafted & Made with <i class="ft-heart pink"></i></span>
  </p>
</footer>

resources/views/layouts/dashboard_student/inc/header.blade.php
@php
  $auth_user = Auth::guard('student')->user();
@endphp
<nav class="header-navbar navbar-expand-md navbar navbar-with-menu navbar-without-dd-arrow fixed-top navbar-light navbar-hide-on-scroll navbar-border navbar-shadow navbar-brand-center">
  <div class="navbar-wrapper">
    <div class="navbar-header">
      <ul class="nav navbar-nav flex-row">
        <li class="nav-item mobile-menu d-md-none mr-auto"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="ft-menu font-large-1"></i></a></li>
        <li class="nav-item">
          <a class="navbar-brand" href="{{ '' }}">
            <img class="brand-logo" alt="modern admin logo" src="{{ asset('dashboard/images/logo/logo.png') }}">
            <h3 class="brand-text">{{ config('app.name') }}</h3>
          </a>
        </li>
        <li class="nav-item d-md-none">
          <a class="nav-link open-navbar-container" data-toggle="collapse" data-target="#navbar-mobile"><i class="la la-ellipsis-v"></i></a>
        </li>
      </ul>
    </div>
    <div class="navbar-container content">
      <div class="collapse navbar-collapse" id="navbar-mobile">
        <ul class="nav navbar-nav mr-auto float-left">
          <li class="nav-item d-none d-md-block"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="ft-menu"></i></a></li>
        </ul>
        <ul class="nav navbar-nav float-right">
          <li class="dropdown dropdown-user nav-item">
            <a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown">
              <span class="mr-1">Hello,
                <span class="user-name text-bold-700">{{ $auth_user->name }}</span>
              </span>
              <span class="avatar avatar-online">
                <img src="{{ $auth_user->img_url('245') }}" alt="avatar">
                <i></i>
              </span>
            </a>
            <form action="{{ route('student.logout') }}" method="post" id="form-logout" class="d-none">@csrf</form>
            <div class="dropdown-menu dropdown-menu-right">
              <a class="dropdown-item" href="{{ route('student.index') }}"><i class="ft-user"></i> Profile</a>
              {{-- <a class="dropdown-item" href="{{ route('admin.activity-log.index') }}"><i class="ft-check-square"></i> Activity Log</a> --}}
              <div class="dropdown-divider"></div>
              <a class="dropdown-item logout-link" href="#"><i class="ft-power"></i> Logout</a>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

resources/views/layouts/dashboard_student/inc/sidebar-item.blade.php
@if ($data->countChildren())
<li class="nav-item">
  <a href="#!">
    <i class="{{ $data->getIcon() }}"></i>
    <span class="menu-title">{{ $data->getText() }}</span>
    {!! $data->generateBadge('badge badge badge-info badge-pill') !!}
  </a>
  <ul class="menu-content">
    @foreach ($data->getChildren() as $r)
    <li class="{{ $r->checkActive() ? 'active' : ''  }}">
      <a class="menu-item" href="{{ $r->getUrl() }}">{{ $r->getText() }}</a>
    </li>
    @endforeach
  </ul>
</li>
@else
<li class="nav-item {{ $data->checkActive() ? 'active' : '' }}">
  <a href="{{ $data->getUrl() }}">
    <i class="{{ $data->getIcon() }}"></i>
    <span class="menu-title">{{ $data->getText() }}</span>
  </a>
</li>
@endif

resources/views/layouts/dashboard_student/inc/sidebar.blade.php
<div class="main-menu menu-static menu-light menu-accordion menu-shadow" data-scroll-to-active="true">
  <div class="main-menu-content">
    <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
      @php
        $item = [
          'text' => 'Dashboard',
          'url'  => 'student.index',
          'icon' => 'la la-dashboard',
        ];
        $menu = new MenuItem($item['text'], $item['url'], $item['icon']);
        $menu->isRoute();
      @endphp
      @include('layouts.dashboard_student.inc.sidebar-item', ['data' => $menu])


  
        <li class="navigation-header center">
            <span>Ujian</span>
            <i class="la la-ellipsis-h ft-minus" data-toggle="tooltip" data-placement="right" data-original-title="Support"></i>
        </li>


        
{{--       
        @php
          $item = [
            'text' => 'Daftar Ujian',
            'url'  => 'student.examination.index',
            'icon' => 'la la-book',
          ];
          $menu = new MenuItem($item['text'], $item['url'], $item['icon']);
          $menu->isRoute();
        @endphp
        @include('layouts.dashboard_student.inc.sidebar-item', ['data' => $menu])
     --}}
    </ul>
  </div>
</div>